AllCops:
  Exclude:
    - bin/**
    - ec2_templater.gemspec
    
# Follow the Jim Weirich school of thought on usage of do/end vs. {...}:
# http://devblog.avdi.org/2011/07/26/the-procedurefunction-block-convention-in-ruby/
Blocks:
  Enabled: false

Documentation:
  Enabled: false
